-- Add equipment slots and enhanced ability data to characters
-- Update the abilities JSONB to include structured ability data
-- Add equipment and backpack columns

-- Add equipment column (items actively worn/used with slots)
ALTER TABLE public.characters 
ADD COLUMN IF NOT EXISTS equipment jsonb DEFAULT '{"weapon": null, "armor": null, "shield": null, "helmet": null, "boots": null, "gloves": null, "ring1": null, "ring2": null, "trinket1": null, "trinket2": null, "trinket3": null}'::jsonb;

-- Add backpack column (all items owned)
ALTER TABLE public.characters 
ADD COLUMN IF NOT EXISTS backpack jsonb DEFAULT '[]'::jsonb;

-- Add resource types (mana, rage, stamina, etc.)
ALTER TABLE public.characters 
ADD COLUMN IF NOT EXISTS resources jsonb DEFAULT '{"mana": 0, "maxMana": 0, "rage": 0, "maxRage": 0, "stamina": 0, "maxStamina": 0}'::jsonb;

-- Add class_description for AI-generated classes
ALTER TABLE public.characters 
ADD COLUMN IF NOT EXISTS class_description text DEFAULT NULL;

-- Add passives for class-based passive abilities
ALTER TABLE public.characters 
ADD COLUMN IF NOT EXISTS passives jsonb DEFAULT '[]'::jsonb;

-- Create table for storing grid state per campaign (authoritative grid)
CREATE TABLE IF NOT EXISTS public.grid_state (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  campaign_id uuid NOT NULL REFERENCES public.campaigns(id) ON DELETE CASCADE,
  grid_size jsonb NOT NULL DEFAULT '{"rows": 10, "cols": 12}'::jsonb,
  tiles jsonb DEFAULT '[]'::jsonb,
  -- Each tile: { x, y, terrain, blocked, occupant_id, occupant_type }
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  UNIQUE(campaign_id)
);

-- Enable RLS on grid_state
ALTER TABLE public.grid_state ENABLE ROW LEVEL SECURITY;

-- RLS policies for grid_state
CREATE POLICY "Campaign members can view grid state" 
ON public.grid_state 
FOR SELECT 
USING (is_campaign_member(auth.uid(), campaign_id) OR is_campaign_owner(auth.uid(), campaign_id));

CREATE POLICY "Campaign members can update grid state" 
ON public.grid_state 
FOR UPDATE 
USING (is_campaign_member(auth.uid(), campaign_id) OR is_campaign_owner(auth.uid(), campaign_id));

CREATE POLICY "Campaign owners can insert grid state" 
ON public.grid_state 
FOR INSERT 
WITH CHECK (is_campaign_owner(auth.uid(), campaign_id));

CREATE POLICY "Campaign owners can delete grid state" 
ON public.grid_state 
FOR DELETE 
USING (is_campaign_owner(auth.uid(), campaign_id));

-- Enable realtime for grid_state
ALTER PUBLICATION supabase_realtime ADD TABLE public.grid_state;

-- Create table for custom abilities (generated by AI)
CREATE TABLE IF NOT EXISTS public.abilities (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  character_id uuid NOT NULL REFERENCES public.characters(id) ON DELETE CASCADE,
  name text NOT NULL,
  description text NOT NULL,
  ability_type text NOT NULL DEFAULT 'active', -- active, passive, reaction
  damage text, -- e.g. "2d6+3" or null for utility
  healing text, -- e.g. "1d8+2"
  range integer DEFAULT 1, -- in grid tiles
  cost integer DEFAULT 0, -- resource cost
  cost_type text DEFAULT 'mana', -- mana, rage, stamina, etc.
  cooldown integer DEFAULT 0, -- turns
  targeting_type text DEFAULT 'single', -- self, single, tile, area, cone, line
  area_size integer DEFAULT 1, -- for area spells
  effects jsonb DEFAULT '[]'::jsonb, -- status effects applied
  is_equipped boolean DEFAULT false, -- can only use if equipped
  created_at timestamp with time zone NOT NULL DEFAULT now()
);

-- Enable RLS on abilities
ALTER TABLE public.abilities ENABLE ROW LEVEL SECURITY;

-- RLS policies for abilities
CREATE POLICY "Users can view their own abilities" 
ON public.abilities 
FOR SELECT 
USING (EXISTS (
  SELECT 1 FROM public.characters c 
  WHERE c.id = abilities.character_id 
  AND (c.user_id = auth.uid() OR is_campaign_member(auth.uid(), c.campaign_id))
));

CREATE POLICY "Users can create abilities for their characters" 
ON public.abilities 
FOR INSERT 
WITH CHECK (EXISTS (
  SELECT 1 FROM public.characters c 
  WHERE c.id = abilities.character_id 
  AND c.user_id = auth.uid()
));

CREATE POLICY "Users can update their own abilities" 
ON public.abilities 
FOR UPDATE 
USING (EXISTS (
  SELECT 1 FROM public.characters c 
  WHERE c.id = abilities.character_id 
  AND c.user_id = auth.uid()
));

CREATE POLICY "Users can delete their own abilities" 
ON public.abilities 
FOR DELETE 
USING (EXISTS (
  SELECT 1 FROM public.characters c 
  WHERE c.id = abilities.character_id 
  AND c.user_id = auth.uid()
));

-- Create table for items (loot database)
CREATE TABLE IF NOT EXISTS public.items (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  name text NOT NULL,
  description text NOT NULL,
  item_type text NOT NULL DEFAULT 'treasure', -- weapon, armor, consumable, treasure, ring, trinket
  slot text, -- weapon, armor, shield, helmet, boots, gloves, ring, trinket
  rarity text NOT NULL DEFAULT 'common', -- common, uncommon, rare, epic, legendary
  stat_modifiers jsonb DEFAULT '{}'::jsonb, -- { "strength": 2, "damage": "+1d6 fire" }
  abilities_granted jsonb DEFAULT '[]'::jsonb, -- ability IDs this item grants
  effects jsonb DEFAULT '[]'::jsonb, -- passive effects
  value integer DEFAULT 0, -- gold value
  created_at timestamp with time zone NOT NULL DEFAULT now()
);

-- Enable RLS on items (public read for item catalog)
ALTER TABLE public.items ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can view items" 
ON public.items 
FOR SELECT 
USING (true);

CREATE POLICY "Only system can insert items" 
ON public.items 
FOR INSERT 
WITH CHECK (false);

-- Update trigger for grid_state updated_at
CREATE TRIGGER update_grid_state_updated_at
BEFORE UPDATE ON public.grid_state
FOR EACH ROW
EXECUTE FUNCTION public.handle_updated_at();

-- Enable realtime for abilities table
ALTER PUBLICATION supabase_realtime ADD TABLE public.abilities;