// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { recordNetworkRequest } from "@/ui/data/networkHealth";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;
const DEV_DEBUG = import.meta.env.DEV;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

if (DEV_DEBUG) {
  const projectRef = SUPABASE_URL?.replace("https://", "").split(".")[0] ?? null;
  console.info("DEV_DEBUG supabase config", {
    hasUrl: Boolean(SUPABASE_URL),
    hasKey: Boolean(SUPABASE_ANON_KEY),
    projectRef,
    url: SUPABASE_URL ?? null,
  });
}

const baseFetch = globalThis.fetch.bind(globalThis);
const debugFetch: typeof fetch = async (input, init) => {
  const url = typeof input === "string" ? input : input.url;
  const method = init?.method ?? "GET";
  if (DEV_DEBUG) {
    console.info("DEV_DEBUG supabase fetch start", { method, url });
  }

  try {
    const response = await baseFetch(input, init);
    if (DEV_DEBUG) {
      console.info("DEV_DEBUG supabase fetch response", {
        method,
        url,
        status: response.status,
      });
    }
    recordNetworkRequest();
    return response;
  } catch (error) {
    if (DEV_DEBUG) {
      console.error("DEV_DEBUG supabase fetch error", { method, url, error });
    }
    recordNetworkRequest();
    throw error;
  }
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    fetch: DEV_DEBUG ? debugFetch : baseFetch,
  },
});

{
  const authAny = supabase.auth as typeof supabase.auth & {
    signInWithPassword?: (...args: Parameters<typeof supabase.auth.signInWithPassword>) => ReturnType<typeof supabase.auth.signInWithPassword>;
  };
  if (authAny.signInWithPassword) {
    const originalSignIn = authAny.signInWithPassword.bind(supabase.auth);
    let inFlight: ReturnType<typeof supabase.auth.signInWithPassword> | null = null;
    authAny.signInWithPassword = async (...args) => {
      const allowed = (globalThis as { __authSubmitInProgress?: boolean }).__authSubmitInProgress === true;
      if (DEV_DEBUG && !allowed) {
        console.warn("[auth] signIn called outside AuthScreen", {
          route: globalThis.location?.pathname ?? null,
        });
      }
      if (inFlight) {
        if (DEV_DEBUG) {
          const count = ((globalThis as { __authTokenGrantCount?: number }).__authTokenGrantCount ?? 0);
          console.info("[auth] log", { step: "sign_in_dedupe", count });
        }
        return inFlight;
      }
      if (DEV_DEBUG) {
        const globalRef = (globalThis as { __authTokenGrantCount?: number });
        globalRef.__authTokenGrantCount = (globalRef.__authTokenGrantCount ?? 0) + 1;
        console.info("[auth] log", { step: "sign_in_start", count: globalRef.__authTokenGrantCount });
      }
      const promise = originalSignIn(...args);
      inFlight = promise;
      try {
        return await promise;
      } finally {
        inFlight = null;
        if (DEV_DEBUG) {
          console.info("[auth] log", { step: "sign_in_end" });
        }
      }
    };
  }
}
