name: "SagaSparkPad"
options:
  createIntermediateGroups: true
settings:
  base:
    SWIFT_VERSION: "5.10"
    CURRENT_PROJECT_VERSION: "1"
    MARKETING_VERSION: "1.0.0"
packages:
  LvlUpKit:
    path: "../../../levelupkit/lvlupkit.package"
targets:
  "SagaSparkPad":
    type: application
    platform: "iOS"
    deploymentTarget: "17.0"
    configFiles:
      Debug: Config/SagaSparkPad.xcconfig
      Release: Config/SagaSparkPad.xcconfig
    info:
      path: Config/Info-SagaSparkPad.plist
      properties:
        CFBundleDisplayName: Saga Spark
        CFBundleName: Saga Spark
        CFBundleURLTypes:
          - CFBundleURLName: com.lvlupkit.sagasparkpad.auth
            CFBundleURLSchemes:
              - sagasparkpad
        DEFAULT_CAMPAIGN_ID: $(DEFAULT_CAMPAIGN_ID)
        LEVELUPKIT_ENABLE_DEV_QUICKSTART: $(LEVELUPKIT_ENABLE_DEV_QUICKSTART)
        LEVELUPKIT_FORCE_DEV_QUICKSTART: $(LEVELUPKIT_FORCE_DEV_QUICKSTART)
        LEVELUPKIT_ENABLE_ANONYMOUS_AUTH: $(LEVELUPKIT_ENABLE_ANONYMOUS_AUTH)
        APP_ENV: $(APP_ENV)
        SUPABASE_ANON_KEY: $(SUPABASE_ANON_KEY)
        SUPABASE_REDIRECT_URL: $(SUPABASE_REDIRECT_URL)
        SUPABASE_URL: $(SUPABASE_URL)
        MYTHIC_FUNCTIONS_BASE_URL: $(MYTHIC_FUNCTIONS_BASE_URL)
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
    sources:
      - path: Sources
    dependencies:
      - package: LvlUpKit
        product: LvlUpKitSagaSparkPad
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: "com.lvlupkit.sagasparkpad"
        TARGETED_DEVICE_FAMILY: "2"
        SUPPORTS_MACCATALYST: NO
        ENABLE_PREVIEWS: NO
        COMPILER_INDEX_STORE_ENABLE: NO
        SUPPORTED_PLATFORMS: iphoneos iphonesimulator
      configs:
        Debug:
          LEVELUPKIT_ENABLE_DEV_QUICKSTART: YES
          LEVELUPKIT_FORCE_DEV_QUICKSTART: NO
          LEVELUPKIT_ENABLE_ANONYMOUS_AUTH: YES
          APP_ENV: dev
        Release:
          LEVELUPKIT_ENABLE_DEV_QUICKSTART: NO
          LEVELUPKIT_FORCE_DEV_QUICKSTART: NO
          LEVELUPKIT_ENABLE_ANONYMOUS_AUTH: YES
          APP_ENV: prod
schemes:
  "SagaSparkPad":
    build:
      targets:
        "SagaSparkPad": all
    run:
      config: Debug
